### PR TITLE
siva: close siva files in ReadOnlyStorer

### LINKED ISSUE #30: Got too many open files errors
When using [`Performance` option](https://github.com/src-d/go-borges/blob/master/siva/library.go#L55-L57) and a lot of repositories, after some queries it fails with too many open files. Check that repository close is being called.

### PR DESCRIPTION
**Pull request by jfontan**
Also close the fs after use in `updateCache`.

Fixes #30

### CODE REVIEW

File: siva/location.go [hunk 1]
```diff
@@ -366,6 +367,7 @@ func (l *Location) Repositories(mode borges.Mode) (borges.RepositoryIterator, er
 			remotes: nil,
 		}, nil
 	}
+	defer repo.Close()
```
Comment (mcarmonaa) [inline siva/location.go]: If the repo is closed here, can we then retrieve the remotes from the config in https://github.com/src-d/go-borges/blob/master/siva/location.go#L374?

Comment (jfontan) [reply siva/location.go]: It's deferred so it's still open when getting the config.
